### PR TITLE
Fix game notes about cities.

### PR DESCRIPTION
**Pull request by asvitkine**
These did not correspond to the actual mechanics per the XML and per what's shown in Unit Help.

No changes to the map logic, just fixing notes.

For reference, this is what unit help shows:
Screen Shot 2022-06-29 at 11 17 35 AM

### CODE REVIEW

**Comment by asvitkine** [comment]
@BeornTheBold FYI (there are also 2 other active pull requests)

**Comment by asvitkine** [comment]
@beelee1 do you have access to merge PRs for this map? I don't seem to have that ability...

**Comment by beelee1** [comment]
@asvitkine sorry just saw this. I'm not sure. It's not giving me an option to here. I did some fixes in the past but I don't remember the exact process. I can merge stuff when it hits the main triplea repo, so can you though, i imagine.

I'll look into what i did and see if i can. Sadly Beorn not around anymore. Pretty involved map. Looks cool but never played it. i think there's still a few unit naming issues as well if i remember right. 

Edit
Ok yea, Dan merged them, so, no i don't. Maybe Dan will bestow some more power on you ? :) 

Edit2
I think issues showed up and then I put a fix in, so more visibility than a pro active fix

**Comment by asvitkine** [comment]
@DanVanAtta do you have merge access?

**Comment by beelee1** [comment]
So this map basically abandoned. If you get it rolling, maybe you can add @Cxnaftalibenporat additions as well ?

**Comment by asvitkine** [comment]
> So this map basically abandoned. If you get it rolling, maybe you can add @Cxnaftalibenporat additions as well ?

Yeah, I understand the author disappeared. Still, I would hope simple fixes like this could just be approved even if the author isn't around. @DanVanAtta do you have access?

**Comment by BeornTheBold** [comment]
Greetings,

I’m the author of Another World.

I’m still around.

*	Byron Spinks

 

 

Americlass Computer Sales & Service, LLC

900 Benton Road

Bossier City, LA 71111

(318) 221-1248 (Office)

(318) 272-1275 (Cell)

(318) 221-7333 (Fax)

***@***.***

**Comment by asvitkine** [comment]
Oh cool! Do you think you can approve some of these fixes?

**Comment by BeornTheBold** [comment]
Sure, I’ll try.  I’m not familiar with github though

 

 

Americlass Computer Sales & Service, LLC

900 Benton Road

Bossier City, LA 71111

(318) 221-1248 (Office)

(318) 272-1275 (Cell)

(318) 221-7333 (Fax)

***@***.***

**Comment by asvitkine** [comment]
@BeornTheBold

Thanks! You should be able to do it through the GitHub website. You need to log in to GitHub, then on a pull request like this one (https://github.com/triplea-maps/another_world/pull/11), there should be a "Merge" button.

**Comment by beelee1** [comment]
Just seeing this. @BeornTheBold Awesome you're still around ! Your map was getting some heavy play for awhile but some units were missing. Mostly when tech was activated. I think the prerelease has a generic missing image now that should keep the map playing. Not a 100 % certain though.

**Comment by asvitkine** [comment]
@ron-murhammer can you merge this one as well?

**Comment by beelee1** [comment]
@BeornTheBold 

Hi @TheDog-GH has done an update to your map for the AI play

**Pull request merged**
